# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Invitationsdepartementet
email: ebba@invitationsdepartementet.se
description: "Äta mat på kvällen och prata svenska."
baseurl: "/test" # the subpath of your site, e.g. /blog
url: "http://test.invitationsdepartementet.se"
pagesurl: http://invitationsdepartementet.github.io
twitter: https://twitter.com/invitationsdept
instagram: https://instagram.com/invitationsdepartementet/
facebook: https://www.facebook.com/invitationsdepartementet
tictail: https://tictail.com/s/invitationsdepartementet
flickr: https://www.flickr.com/photos/unitedinvitations/albums
vimeo: https://vimeo.com/user44433198
# Link to main video
vimeourl: https://vimeo.com/141152511
# Build settings
markdown: kramdown
support: malcolm@invitationsdepartementet.se